<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>Strathweb.A2UI.A2A.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Strathweb.A2UI.A2A\Strathweb.A2UI.A2A.csproj" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

</Project>
